<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Testing Chrome"
           tests="6"
           failures="2"
           errors="0"
           skipped="0"
           time="13.207">
    <properties></properties>

            <testcase
                name="tc0010_validate_product_price_test"
                time="5.282"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">

            <failure type="java.lang.AssertionError" message="expected [$34.95 USD] but found [null]">
                <![CDATA[java.lang.AssertionError: expected [$34.95 USD] but found [null]
                org.testng.Assert.fail(Assert.java:96)org.testng.Assert.failNotEquals(Assert.java:776)org.testng.Assert.assertEqualsImpl(Assert.java:132)org.testng.Assert.assertEquals(Assert.java:118)org.testng.Assert.assertEquals(Assert.java:453)org.testng.Assert.assertEquals(Assert.java:463)com.alexnova.kathi.oke.testcases.ProductAddToCartTests.tc0010_validate_product_price_test(ProductAddToCartTests.java:54)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.Invoker.invokeMethod(Invoker.java:583)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:648)org.testng.TestRunner.run(TestRunner.java:505)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>
            <testcase
                name="tc0015_verify_quantity_matches_cost_in_cart_test"
                time="2.360"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">

            <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
                <![CDATA[java.lang.AssertionError: expected [true] but found [false]
                org.testng.Assert.fail(Assert.java:96)org.testng.Assert.failNotEquals(Assert.java:776)org.testng.Assert.assertTrue(Assert.java:44)org.testng.Assert.assertTrue(Assert.java:54)com.alexnova.kathi.oke.testcases.ProductAddToCartTests.tc0015_verify_quantity_matches_cost_in_cart_test(ProductAddToCartTests.java:133)sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)java.lang.reflect.Method.invoke(Method.java:498)org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)org.testng.internal.Invoker.invokeMethod(Invoker.java:583)org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)org.testng.TestRunner.privateRun(TestRunner.java:648)org.testng.TestRunner.run(TestRunner.java:505)org.testng.SuiteRunner.runTest(SuiteRunner.java:455)org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)org.testng.SuiteRunner.run(SuiteRunner.java:364)org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)org.testng.TestNG.runSuitesLocally(TestNG.java:1137)org.testng.TestNG.runSuites(TestNG.java:1049)org.testng.TestNG.run(TestNG.java:1017)com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
            </failure>
    </testcase>


            <testcase
                name="tc0011_validate_product_add_to_cart_test"
                time="2.845"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">
            </testcase>
            <testcase
                name="tc0013_quantity_increase_in_cart_test"
                time="1.723"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">
            </testcase>
            <testcase
                name="tc0014_verify_quantity_matches_cost_in_cart_test"
                time="0.104"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">
            </testcase>
            <testcase
                name="tc0012_validate_product_present_in_cart_test"
                time="0.893"
                classname="com.alexnova.kathi.oke.testcases.ProductAddToCartTests">
            </testcase>
</testsuite>
